# Generated by Django 2.0.5 on 2018-05-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('matrix_server', models.CharField(max_length=100)),
                ('matrix_client', models.CharField(max_length=100)),
                ('matrix_user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('matrix_room_name', models.CharField(default='', max_length=100)),
                ('message_count', models.IntegerField(default=1)),
                ('show_images', models.BooleanField(default=False)),
                ('matrix_token', models.CharField(max_length=1000)),
                ('matrix_sync_token', models.CharField(max_length=200)),
                ('messages', models.TextField(null=True)),
            ],
        ),
    ]
