# Generated by Django 2.0.5 on 2018-05-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='matrix_room_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
