# Generated by Django 2.0.5 on 2018-05-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_session_matrix_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='message_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='session',
            name='messages',
            field=models.TextField(null=True),
        ),
    ]
