# Generated by Django 2.0.5 on 2018-05-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_auto_20180512_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='message_count',
            field=models.IntegerField(default='1'),
        ),
    ]
