# Generated by Django 2.0.5 on 2018-05-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_auto_20180513_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='message_count',
            field=models.IntegerField(default=1),
        ),
    ]
