# Generated by Django 2.0.5 on 2018-05-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_auto_20180513_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='matrix_token',
            field=models.CharField(max_length=1000),
        ),
    ]
