# Generated by Django 2.0.5 on 2018-05-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_auto_20180513_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AlterField(
            model_name='session',
            name='matrix_user_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
