# Generated by Django 2.0.5 on 2018-05-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_auto_20180514_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='show_images',
            field=models.BooleanField(default=False),
        ),
    ]
